### PR TITLE
Upgrade to PHP >= 7.3 and PHPUnit 8.5

### PR DESCRIPTION
**Pull request by Surfoo**
Hello,

Here is an upgrade of geotools and a new format of coordinates frequently used.

Please review this PR. I'd like to use it without create my own fork.
Maybe you can release as `1.0.0` (It's a breaking change I think)

### CODE REVIEW

**Comment by Nyholm** [comment]
Hey. Thank you for this PR. It looks like you are doing a lot of CS changes too. That makes it impossible to review. Please revert them. 

What are the PHP 7.3 features we cannot live without? Why not use 7.2?

**Comment by Surfoo** [comment]
Hello @Nyholm,

Thanks for your comments!
I thought it was a good idea to upgrade to PHP 7.3 because PHP 7.2 is near of his end of live (about 5 months). Also, I when I upgraded PHPUnit to the latest version, [it doesn't support PHP 7.2](https://phpunit.de/supported-versions.html).

About PHP-CS-Fixer, sorry, It's globally installed on my editor (formatOnSave) and fix a lot of files by default. So, I thought it was a good idea to have some coding standards and I added the configuration file.
It's very long to revert them now... maybe we may discuss about them and update the rules?

**Comment by Nyholm** [comment]
I cannot merge a PR without a review. 

Making multiple changes (bump deps and CS) in the same PR is not a good idea because it makes the diff too big.

**Comment by Surfoo** [comment]
Multiple commits will be OK?

**Comment by Nyholm** [comment]
Yeah, I dont care how many commits there are. They will be squashed. 

As long as one PR is doing one thing. Diffs should be as small as possible.

**Comment by Surfoo** [comment]
@Nyholm Done, I upgraded only to PHPUnit 8.5 for this PR. tests passed.

PHPUnit 9 needs to remove expections annotations:
```The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageRegExp() instead.```

Maybe an other PR?

**Comment by Surfoo** [comment]
friendly ping @Nyholm :)

**Comment by canvural** [comment]
@Nyholm Any update on this? I'm willing to also work on PHP8 support and having this PR would make that job easier.

**Comment by Surfoo** [comment]
How can we work for this repository without waiting for someone? Do you accept new developers in the phpleague team? I'll be glad to maintain the geotools library.

**Comment by Nyholm** [comment]
Excellent questions. I’ll have a look at this pr to get things moving. I’ll also ping someone with access to promote contributors.

**Review by Nyholm — APPROVED** [review]
Thank you

**Comment by canvural** [comment]
Thank you @Nyholm

**Comment by Surfoo** [comment]
> Excellent questions. I’ll have a look at this pr to get things moving. I’ll also ping someone with access to promote contributors.

Hello @Nyholm, do you have any news about my questions?

**Pull request merged**
