### PR TITLE
React/promise instead of react/async (deprecated)

### PR DESCRIPTION
**Pull request by morrislaptop**

### CODE REVIEW

**Comment by morrislaptop** [comment]
Failed test is because of daily limit reached

**Comment by toin0u** [comment]
@morrislaptop That looks really good :+1: <3 Can you squash your commits ?

**Comment by morrislaptop** [comment]
Squashed :)

**Comment by toin0u** [comment]
@morrislaptop Thank you very much :) :+1:

**Comment by arnold-almeida** [comment]
:+1:

**Pull request merged**
