### PR TITLE
Prepare for 0.8.0

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by nabeelio** [comment]
So far it looks good. I have a bunch of tests for the closest between multiple points and center points and they are all passing without change. I will check the maps and stuff that are generated later, since they utilize a lot of the geotools stuff for plotting proper flight routes.

**Comment by Nyholm** [comment]
Excellent. Thank you!

**Comment by nabeelio** [comment]
Hey, the maps in my project are all looking fine and the calculations and stuff seem to be all in order. Thanks for updating!

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
