### PR TITLE
Addresses Issue #94

### PR DESCRIPTION
**Pull request by stevendesu**
I went ahead and wrapped this up to address my own issue

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. Could you rebase this and check why the tests fails?

**Comment by stevendesu** [comment]
Will rebase and start to look into this tonight or tomorrow.

**Comment by Nyholm** [comment]
Awesome. Thank you.

**Comment by stevendesu** [comment]
This has been rebased onto master. Pending unit tests

**Pull request merged**
