### PR TITLE
Update to willdurand/geocoder with ~3.0@alpha

### PR DESCRIPTION
**Pull request by morrislaptop**
With tests :) For #52

### CODE REVIEW

**Comment by arnold-almeida** [comment]
Nice work!

**Comment by toin0u** [comment]
That's awesome @morrislaptop ! :heart:

**Comment by toin0u** [comment]
This will be definitely merged when Geocoder 3 will be released :dancer:

**Comment by morrislaptop** [comment]
Hopefully soon! @willdurand

**Comment by collmomo** [comment]
Is it possible to clone what @morrislaptop did or can you guys release an alpha version based even though the stable is not yet ready ?

**Comment by jverdeyen** [comment]
Any update on this? Can we create a alpha release branch for this? Thanks!

**Comment by toin0u** [comment]
@jverdeyen Well Geocoder 3 is released so yes it's a good idea :) Can you update the PR @morrislaptop please ? :)

**Comment by willdurand** [comment]
:+1:

**Comment by morrislaptop** [comment]
It was a bit of PITA because of #54 but this should be good to go :+1:

**Comment by amenadiel** [comment]
+1

**Comment by morrislaptop** [comment]
@toin0u is this going to be merged in?!

**Comment by toin0u** [comment]
@morrislaptop I'm sorry - I was very busy lately... Thank you! <3

**Comment by amenadiel** [comment]
@toin0u @morrislaptop  for some reason, Packagist is still listing version 2.4 as a dependence.

https://packagist.org/packages/league/geotools#dev-master

Could we get a version bump, perhaps in the form of a 0.4.1 tag?

Thanks!

**Comment by toin0u** [comment]
@amenadiel I would like to push to 1.0 as soon as poassible actually :)

**Comment by amenadiel** [comment]
php geocoder has released its version 3.2.0.
https://github.com/geocoder-php/Geocoder/releases/tag/v3.2.0

Can we get a tag bump, pretty pretty please?

**Comment by toin0u** [comment]
@amenadiel https://github.com/thephpleague/geotools/commit/a6883975b40d5b0bfb0933ee4243073164244eb3

I will tag it 0.5 not 1.0 because I would like to change some stuff before..

**Comment by toin0u** [comment]
@amenadiel https://github.com/thephpleague/geotools/releases/tag/0.5.0 :)

**Comment by willdurand** [comment]
👍

**Comment by amenadiel** [comment]
@toin0u  :+1 excellent!

**Pull request merged**
