### PR TITLE
Add all Vertex method declarations to VertexInterface

### PR DESCRIPTION
**Pull request by theomessin**
A lot of methods are missing from the interface (and all your methods return an interface). This causes issues with intellisense:

### CODE REVIEW

**Comment by theomessin** [comment]
How exactly is this project part of the The PHP League?

**Comment by Surfoo** [comment]
ping @Nyholm :)

**Review by Nyholm — CHANGES_REQUESTED** [review]
This is a massive BC break. 

What is the reason for this change? Could you make an argument for this change with interface segregation principle in mind?

**Comment by theomessin** [comment]
Don't really need this anymore.

**Pull request closed without merging**
